[base]
env_name = conformer_gen

[env]
# 0 = alkanes, 1 = lignins, 2 = both. Only *_train dataset folders are loaded.
molecule_family = 0

[vec]
total_agents = 1024
num_buffers = 4
num_threads = 16

[policy]
hidden_size = 512
num_layers = 3

[train]
total_timesteps = 500_000_000
; horizon = 64
; minibatch_size = 16384
; gamma = 0.995
; gae_lambda = 0.96
; learning_rate = 0.00015
learning_rate = 0.0004573146765703167
gamma = 0.7647543366891623
gae_lambda = 0.996005622445478
max_grad_norm = 0.6075578331947327
vf_coef = 0.3979089612467003
horizon = 64
ent_coef = 0.01210084358004069
minibatch_size = 32768

[sweep]
sweep_only = horizon, gamma, gae_lambda, learning_rate, ent_coef, clip_coef, vf_coef, vf_clip_coef
gpus = 4
max_runs = 1200

[sweep.train.horizon]
distribution = uniform_pow2
min = 64
max = 128
scale = 1.0

[sweep.train.learning_rate]
distribution = log_normal
min = 5e-5
max = 3e-4
scale = auto

[sweep.train.ent_coef]
distribution = log_normal
min = 5e-4
max = 5e-3
scale = auto

[sweep.train.gamma]
distribution = logit_normal
min = 0.985
max = 0.9995
scale = auto

[sweep.train.gae_lambda]
distribution = logit_normal
min = 0.85
max = 0.985
scale = auto

[sweep.train.clip_coef]
distribution = uniform
min = 0.02
max = 0.12
scale = auto

[sweep.train.vf_coef]
distribution = uniform
min = 1.0
max = 4.0
scale = auto

[sweep.train.vf_clip_coef]
distribution = uniform
min = 1.0
max = 5.0
scale = auto
